name: place_nav_search
description: Flutter project For testing google map's funtionality.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  audioplayer: ^0.8.1
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  fab_circular_menu: ^1.0.2
  flip_card: ^0.6.0
  flutter:
    sdk: flutter
  flutter_polyline_points: ^1.0.0
  flutter_rating_stars: ^1.0.3+4
  flutter_riverpod: ^2.1.0
  google_maps_flutter: ^2.2.1
  http: ^0.13.5
  lottie: ^1.4.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/animassets/mapanimation.json
    - assets/mapicons/
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Italic.ttf
          style: italic
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-Light.ttf
          weight: 200
        - asset: assets/fonts/WorkSans-Thin.ttf
          weight: 300
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 400
        - asset: assets/fonts/WorkSans-ExtraLight.ttf
          weight: 100



